# Generated by Django 3.0 on 2019-12-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='item',
        ),
    ]
